apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodejs-app
spec:
  ports:
  - name: "http"
    port: {{ .Values.nodejsApp.port }}
    targetPort: {{ .Values.nodejsApp.port }}
  selector:
    app: nodejs-app
