kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: kdphad/nodejs-app
        ports:
        - containerPort: 3000
        - name: nodejs-app
          image: {{ .Values.nodejsApp.image }}
          ports:
            - containerPort: {{ .Values.nodejsApp.port }}
