apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-my-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /mongodb
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mongodb
                port:
                  number: 27017
          - path: /nodejs-app
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-nodejs-app
                port:
                  number: {{ .Values.nodejsApp.port }}
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-redis
                port:
                  number: 6379
